### ISSUE TITLE
Generation adjustments - Android

### ISSUE THREAD

**Issue by trmi1012** [pace/SwagGen#43]
There are a few things we currently adjust manually due to wrong generation. 

- [x] Delete `Errors` classes

- [ ] Delete `Data` classes and add `@JsonApi` Annotations

- [ ] Return type of `GetUserPreferences` Request

- [ ] Add `@JVMSuppressWildcards` to `UpdateUserPreferences` Request

- [ ] `GetTermsAPI`'s accept and content type (null, application/vnd.api+json)

- [ ] Change `gasStation` and `gasStationNote` type from `HasMany<>` to `HasOne<>`

**Comment by EmDee** [comment]
Done.
