### ISSUE TITLE
Remove Alamofire dependency

### ISSUE THREAD

**Issue by EmDee** [pace/SwagGen#5]

**Comment by EmDee** [comment]
@telip007 Do you have a rough estimate how much work it would take to replace `Alamofire`? I just had a quick skim through the template and it doesn't look like it's a lot to replace.

**Comment by telip007** [comment]
Well we would need to rewrite the session handling and request execution. I would say roughly two days...

**Comment by EmDee** [comment]
Sounds good. This is something we should tackle next then.
