### ISSUE TITLE
Fix Discount relationship in Transaction model and APIs

### ISSUE THREAD

**Issue by Melle010** [pace/SwagGen#73]
The `discountTokens` relationship is missing in the `Transaction` model of the 2022-1 fueling API:

### Expected

Transaction:

```
private var discountTokens: HasMany<Discount> = HasMany()
fun getDiscountTokens() = discountTokens.get(document)
```

ListTransactionsAPI, GetTransactionAPI, ProcessPaymentAPI:
Generates and passes the following resources list to the Retrofit client:

```
val resources = listOf(Discount::class.java)
val headers = headers(...)

return retrofit(..., resources)
```

**Comment by EmDee** [comment]
Similar issue: https://github.com/pace/SwagGen/pull/72

**Comment by Melle010** [comment]
Moved to GitLab.
